/**
 * Suggestions used in our medical intake during onboarding.
 * Only use the drug suggestions currently.
 */
export const conditionSuggestions = [
  "Congestive heart failure",
  "Atrial fibrillation",
  "Paroxysmal supraventricular tachycardia",
  "Premature ventricular contractions",
  "Aortic valve regurgitation",
  "Aortic valve stenosis",
  "Endocarditis",
  "Mitral valve regurgitation",
  "Mitral valve stenosis",
  "Mitral valve prolapse",
  "Aortic aneurysm",
  "Heart infections",
];
export const drugSuggestions = [
  "Abilify",
  "Acetaminophen",
  "Acetaminophen and Hydrocodone",
  "Actos",
  "Acyclovir",
  "Adderall",
  "Adderall XR",
  "Advair",
  "Advair Diskus",
  "Advil",
  "Aimovig",
  "Albuterol",
  "Aldactone",
  "Alendronate",
  "Aleve",
  "Allegra",
  "Allopurinol",
  "Alprazolam",
  "Amantadine",
  "Ambien",
  "Amiodarone",
  "Amitiza",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin and Clavulanate",
  "Anastrozole",
  "Apixaban",
  "Aricept",
  "Aripiprazole",
  "Aspirin",
  "Atarax",
  "Atenolol",
  "Ativan",
  "Atorvastatin",
  "Atropine",
  "Augmentin",
  "Azathioprine",
  "Azelastine",
  "Azithromycin",
  "Bacitracin",
  "Baclofen",
  "Bactrim",
  "Bactrim DS",
  "Bactroban",
  "Basaglar",
  "Belbuca",
  "Belsomra",
  "Belviq",
  "Benadryl",
  "Benazepril",
  "Benicar",
  "Bentyl",
  "Benzonatate",
  "Benztropine",
  "Betamethasone",
  "Bethanechol",
  "Bevacizumab",
  "Biaxin",
  "Bicalutamide",
  "Biktarvy",
  "Biotin",
  "Bisacodyl",
  "Bisoprolol",
  "Boniva",
  "Botox",
  "Breo Ellipta",
  "Brilinta",
  "Brimonidine",
  "Budesonide",
  "Bumetanide",
  "Bumex",
  "Buprenorphine",
  "Buprenorphine and Naloxone",
  "Bupropion",
  "Buspar",
  "Buspirone",
  "Butrans",
  "Bydureon",
  "Bystolic",
  "Calcitriol",
  "Carafate",
  "Carbamazepine",
  "Cardizem",
  "Carvedilol",
  "Cefdinir",
  "Ceftriaxone",
  "Cefuroxime",
  "Celebrex",
  "Celecoxib",
  "Celexa",
  "Cephalexin",
  "Cetirizine",
  "Chantix",
  "Chlorthalidone",
  "Cholecalciferol",
  "Cialis",
  "Cilostazol",
  "Cipro",
  "Ciprofloxacin",
  "Citalopram",
  "Clarithromycin",
  "Claritin",
  "Clindamycin",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Codeine",
  "Colace",
  "Colchicine",
  "Compazine",
  "Concerta",
  "Coreg",
  "Coumadin",
  "Cozaar",
  "Crestor",
  "Cyanocobalamin",
  "Cyclobenzaprine",
  "Cymbalta",
  "Debrox",
  "Decadron",
  "Demerol",
  "Depakote",
  "Depo - Provera",
  "Desloratadine",
  "Desmopressin",
  "Desvenlafaxine",
  "Dexamethasone",
  "Dexilant",
  "Dextroamphetamine",
  "Dextromethorphan",
  "Diazepam",
  "Diclofenac",
  "Diclofenac Sodium",
  "Dicyclomine",
  "Diflucan",
  "Digoxin",
  "Dilantin",
  "Dilaudid",
  "Diltiazem",
  "Diovan",
  "Diphenhydramine",
  "Ditropan",
  "Divalproex",
  "Divalproex sodium",
  "Docusate",
  "Docusate Sodium",
  "Domperidone",
  "Donepezil",
  "Dopamine",
  "Doxazosin",
  "Doxepin",
  "Doxycycline",
  "Dulcolax",
  "Dulera",
  "Duloxetine",
  "DuoNeb",
  "Dupixent",
  "Dutasteride",
  "Ecotrin",
  "Effexor",
  "Effexor XR",
  "Effient",
  "Elavil",
  "Elidel",
  "Eligard",
  "Eliquis",
  "Elmiron",
  "Elocon",
  "Emgality",
  "Empagliflozin",
  "Enalapril",
  "Enbrel",
  "Enoxaparin",
  "Entresto",
  "Entyvio",
  "Epclusa",
  "Ephedrine",
  "Epidiolex",
  "Epinephrine",
  "EpiPen",
  "Eplerenone",
  "Epogen",
  "Ergocalciferol",
  "Ertapenem",
  "Erythromycin",
  "Escitalopram",
  "Escitalopram Oxalate",
  "Esomeprazole",
  "Estrace",
  "Estradiol",
  "Eszopiclone",
  "Etodolac",
  "Eucrisa",
  "Evista",
  "Excedrin",
  "Exelon",
  "Exemestane",
  "Ezetimibe",
  "Famciclovir",
  "Famotidine",
  "Farxiga",
  "Febuxostat",
  "Felodipine",
  "Femara",
  "Fenofibrate",
  "Fentanyl",
  "Ferrous gluconate",
  "Ferrous Sulfate",
  "Fexofenadine",
  "Finasteride",
  "Fioricet",
  "Fish Oil",
  "Flagyl",
  "Flecainide",
  "Flexeril",
  "Flomax",
  "Flonase",
  "Florastor",
  "Flovent",
  "Flovent HFA",
  "Fluconazole",
  "Fludrocortisone",
  "Fluocinonide",
  "Fluorouracil",
  "Fluoxetine",
  "Fluphenazine",
  "Fluticasone",
  "Fluticasone Propionate",
  "Fluticasone and salmeterol",
  "Fluvoxamine",
  "Focalin",
  "Focalin XR",
  "Folic Acid",
  "Forteo",
  "Fosamax",
  "Fosfomycin",
  "Fosinopril",
  "Furosemide",
  "Gabapentin",
  "Galantamine",
  "Gammagard",
  "Garlic",
  "Gaviscon",
  "Gemcitabine",
  "Gemfibrozil",
  "Gemzar",
  "Genotropin",
  "Gentamicin",
  "Gentamicin ophthalmic",
  "Genvoya",
  "Geodon",
  "Gilenya",
  "Ginkgo",
  "Ginkgo biloba",
  "Ginseng",
  "Gleevec",
  "Glimepiride",
  "Glipizide",
  "Glipizide and metformin",
  "Glucagon",
  "Glucophage",
  "Glucosamine",
  "Glucotrol",
  "Glucovance",
  "Glumetza",
  "Glutamine",
  "Glutathione",
  "Glyburide",
  "GlycoLax",
  "Glycopyrrolate",
  "Glyxambi",
  "GoLYTELY",
  "Gralise",
  "Granisetron",
  "Granix",
  "Griseofulvin",
  "Guaifenesin",
  "Guanfacine",
  "Halcion",
  "Haldol",
  "Haldol Decanoate",
  "Haloperidol",
  "Harvoni",
  "Heparin",
  "Heparin Sodium",
  "Herceptin",
  "Hiprex",
  "Hizentra",
  "Horizant",
  "Humalog",
  "Humira",
  "Humulin 70 / 30",
  "Humulin N",
  "Humulin R",
  "Hycodan",
  "Hydralazine",
  "Hydrea",
  "Hydrochlorothiazide",
  "Hydrochlorothiazide and irbesartan",
  "Hydrochlorothiazide and lisinopril",
  "Hydrochlorothiazide and losartan",
  "Hydrochlorothiazide and olmesartan",
  "Hydrochlorothiazide and triamterene",
  "Hydrochlorothiazide and valsartan",
  "Hydrocodone",
  "Hydrocodone and acetaminophen",
  "Hydrocortisone",
  "Hydrocortisone topical",
  "Hydromorphone",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "Hydroxyzine",
  "Hydroxyzine Hydrochloride",
  "Hydroxyzine Pamoate",
  "Hyoscyamine",
  "Hysingla ER",
  "Hytrin",
  "Hyzaar",
  "Ibandronate",
  "Ibrance",
  "Ibrutinib",
  "Ibuprofen",
  "Imatinib",
  "Imbruvica",
  "Imdur",
  "Imipramine",
  "Imitrex",
  "Imodium",
  "Imodium A - D",
  "Imuran",
  "Incruse Ellipta",
  "Indapamide",
  "Inderal",
  "Indocin",
  "Indomethacin",
  "Infliximab",
  "Ingrezza",
  "Injectafer",
  "Insulin",
  "Insulin glargine",
  "Insulin lispro",
  "Insulin regular",
  "Intuniv",
  "Invanz",
  "Invega",
  "Invega Sustenna",
  "Invokana",
  "Ipratropium",
  "Ipratropium Bromide",
  "Irbesartan",
  "Isoniazid",
  "Isosorbide",
  "Isosorbide dinitrate",
  "Isosorbide mononitrate",
  "Isotretinoin",
  "Itraconazole",
  "Ivabradine",
  "Ivermectin",
  "Jadenu",
  "Jakafi",
  "Jalyn",
  "Jantoven",
  "Janumet",
  "Janumet XR",
  "Januvia",
  "Jardiance",
  "Jencycla",
  "Jentadueto",
  "Jentadueto XR",
  "Jeuveau",
  "Jevtana",
  "Jinteli",
  "Jolessa",
  "Jolivette",
  "Jornay PM",
  "Jublia",
  "Juleber",
  "Juluca",
  "Junel",
  "Junel 1 / 20",
  "Junel 1.5 / 30",
  "Junel Fe 1 / 20",
  "Junel Fe 1.5 / 30",
  "Junel Fe 24",
  "Juvederm",
  "Juxtapid",
  "Jynarque",
  "Kadcyla",
  "Kadian",
  "Kaletra",
  "Kalydeco",
  "Kanamycin",
  "Kaopectate",
  "Kapspargo Sprinkle",
  "Kapvay",
  "Kariva",
  "Kayexalate",
  "Kcentra",
  "K - Dur",
  "Keflex",
  "Kenalog",
  "Kenalog - 40",
  "Keppra",
  "Keppra XR",
  "Ketamine",
  "Ketoconazole",
  "Ketoconazole Shampoo",
  "Ketoconazole topical",
  "Ketoprofen",
  "Ketorolac",
  "Ketorolac ophthalmic",
  "Ketorolac Tromethamine",
  "Ketotifen",
  "Ketotifen ophthalmic",
  "Kevzara",
  "Keytruda",
  "Kineret",
  "Kisqali",
  "Klonopin",
  "Klor - Con",
  "Kombiglyze XR",
  "Kratom",
  "Kristalose",
  "K - Tab",
  "Kyleena",
  "Kymriah",
  "Kyprolis",
  "Labetalol",
  "Lactulose",
  "Lamictal",
  "Lamisil",
  "Lamotrigine",
  "Lansoprazole",
  "Lantus",
  "Lasix",
  "Latanoprost",
  "Latuda",
  "Leflunomide",
  "Letrozole",
  "Levaquin",
  "Levemir",
  "Levetiracetam",
  "Levitra",
  "Levocetirizine",
  "Levofloxacin",
  "Levothyroxine",
  "Lexapro",
  "Lidocaine",
  "Linzess",
  "Lipitor",
  "Lisinopril",
  "Lithium",
  "Livalo",
  "Lomotil",
  "Loperamide",
  "Lopressor",
  "Loratadine",
  "Lorazepam",
  "Lortab",
  "Losartan",
  "Lovastatin",
  "Lovaza",
  "Lovenox",
  "Lumigan",
  "Lunesta",
  "Lupron",
  "Lyrica",
  "Macrobid",
  "Magnesium oxide",
  "Meclizine",
  "Medrol",
  "Medrol Dosepak",
  "Melatonin",
  "Meloxicam",
  "Memantine",
  "Meropenem",
  "Mesalamine",
  "Metamucil",
  "Metaxalone",
  "Metformin",
  "Methadone",
  "Methimazole",
  "Methocarbamol",
  "Methotrexate",
  "Methylphenidate",
  "Methylprednisolone",
  "Metoclopramide",
  "Metolazone",
  "Metoprolol",
  "Metoprolol Succinate ER",
  "Metoprolol Tartrate",
  "Metronidazole",
  "Midazolam",
  "Midodrine",
  "Minocycline",
  "MiraLax",
  "Mirapex",
  "Mirtazapine",
  "Mobic",
  "Modafinil",
  "Montelukast",
  "Morphine",
  "Motrin",
  "Mucinex",
  "Mupirocin",
  "Mupirocin topical",
  "Myrbetriq",
  "Nabumetone",
  "Nadolol",
  "Naloxone",
  "Naltrexone",
  "Namenda",
  "Namzaric",
  "Naprosyn",
  "Naproxen",
  "Narcan",
  "Nasacort",
  "Nasonex",
  "Nebivolol",
  "Neomycin",
  "Neosporin",
  "Neulasta",
  "Neurontin",
  "Nexium",
  "Nexplanon",
  "Niacin",
  "Niaspan",
  "Nicotine",
  "Nifedipine",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Nitrostat",
  "Nivolumab",
  "Norco",
  "Norepinephrine",
  "Norethindrone",
  "Norflex",
  "Nortriptyline",
  "Norvasc",
  "NovoLog",
  "NP Thyroid",
  "Nucala",
  "Nucynta",
  "Nuedexta",
  "NuvaRing",
  "Nuvigil",
  "Nystatin",
  "Ocrevus",
  "Octreotide",
  "Ocuvite",
  "Odefsey",
  "Ofloxacin",
  "Ofloxacin ophthalmic",
  "Olanzapine",
  "Olaparib",
  "Olmesartan",
  "Olmesartan Medoxomil",
  "Olopatadine ophthalmic",
  "Omega - 3 polyunsaturated fatty acids",
  "Omeprazole",
  "Omnicef",
  "Ondansetron",
  "Onfi",
  "Onglyza",
  "Opana",
  "Opdivo",
  "Orencia",
  "Orilissa",
  "Orlistat",
  "Orphenadrine",
  "Ortho Tri - Cyclen",
  "Orthovisc",
  "Oseltamivir",
  "Osimertinib",
  "Otezla",
  "Oxaliplatin",
  "Oxaprozin",
  "Oxazepam",
  "Oxcarbazepine",
  "Oxybutynin",
  "Oxycodone",
  "Oxycontin",
  "Oxygen",
  "Oxymetazoline nasal",
  "Oxymorphone",
  "Oxytocin",
  "Ozempic",
  "Pantoprazole",
  "Paracetamol",
  "Paroxetine",
  "Paxil",
  "Penicillin",
  "Pepcid",
  "Percocet",
  "Phenazopyridine",
  "Phenergan",
  "Phenobarbital",
  "Phentermine",
  "Phenytoin",
  "Pioglitazone",
  "Plaquenil",
  "Plavix",
  "Polyethylene glycol 3350",
  "Potassium Chloride",
  "Pradaxa",
  "Pramipexole",
  "Pravastatin",
  "Prazosin",
  "Prednisolone",
  "Prednisone",
  "Pregabalin",
  "Premarin",
  "Prevacid",
  "Prilosec",
  "Primidone",
  "Pristiq",
  "ProAir HFA",
  "Prochlorperazine",
  "Progesterone",
  "Prolia",
  "Promethazine",
  "Propofol",
  "Propranolol",
  "Protonix",
  "Prozac",
  "Pseudoephedrine",
  "Pyridium",
  "Qbrexza",
  "QNASL",
  "Qsymia",
  "Qtern",
  "Qternmet XR",
  "Qualaquin",
  "Quasense",
  "Quazepam",
  "Qudexy XR",
  "Quercetin",
  "Questran",
  "Questran Light",
  "Quetiapine",
  "Quetiapine Fumarate",
  "QuilliChew ER",
  "Quillivant XR",
  "Quinapril",
  "Quinapril Hydrochloride",
  "Quinidine",
  "Quinine",
  "Quinine Sulfate",
  "Qutenza",
  "Qvar",
  "Qvar Redihaler",
  "Rabeprazole",
  "Raloxifene",
  "Ramipril",
  "Ranexa",
  "Ranitidine",
  "Ranolazine",
  "Rapaflo",
  "Rasagiline",
  "Reclast",
  "Reglan",
  "Relafen",
  "Relpax",
  "Remeron",
  "Remicade",
  "Renvela",
  "Repaglinide",
  "Repatha",
  "Requip",
  "Restasis",
  "Restoril",
  "Revlimid",
  "Rexulti",
  "Rifampin",
  "Rifaximin",
  "Risedronate",
  "Risperdal",
  "Risperidone",
  "Ritalin",
  "Rituxan",
  "Rituximab",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Robaxin",
  "Robitussin",
  "Rocephin",
  "Ropinirole",
  "Rosuvastatin",
  "Roxicodone",
  "Rozerem",
  "Salbutamol",
  "Savella",
  "Saxenda",
  "Scopolamine",
  "Senna",
  "Senokot",
  "Sensipar",
  "Septra",
  "Seroquel",
  "Seroquel XR",
  "Sertraline",
  "Sevelamer",
  "Shingrix",
  "Sildenafil",
  "Simethicone",
  "Simvastatin",
  "Sinemet",
  "Singulair",
  "Sitagliptin",
  "Skelaxin",
  "Sodium bicarbonate",
  "Sodium chloride",
  "Soliqua",
  "Solu - Medrol",
  "Soma",
  "Sotalol",
  "Spiriva",
  "Spironolactone",
  "Sprintec",
  "Stelara",
  "Strattera",
  "Suboxone",
  "Subutex",
  "Sucralfate",
  "Sudafed",
  "Sulfamethoxazole and trimethoprim",
  "Sulfasalazine",
  "Sumatriptan",
  "Symbicort",
  "Synthroid",
  "Tacrolimus",
  "Tadalafil",
  "Tamiflu",
  "Tamoxifen",
  "Tamsulosin",
  "Tegretol",
  "Telmisartan",
  "Temazepam",
  "Terazosin",
  "Terbinafine",
  "Tessalon Perles",
  "Testosterone",
  "Tetracycline",
  "Theophylline",
  "Thiamine",
  "Timolol",
  "Tizanidine",
  "Tobramycin",
  "Tolterodine",
  "Topamax",
  "Topiramate",
  "Toprol XL",
  "Toradol",
  "Torsemide",
  "Tradjenta",
  "Tramadol",
  "Trazodone",
  "Trelegy Ellipta",
  "Tresiba",
  "Tretinoin",
  "Triamcinolone",
  "Triamterene",
  "Trileptal",
  "Trimethoprim",
  "Trintellix",
  "Trulicity",
  "Truvada",
  "Turmeric",
  "Tylenol",
  "Tylenol with Codeine #3",
  "Ubiquinone",
  "Uceris",
  "Udenyca",
  "Ulipristal",
  "Uloric",
  "Ultane",
  "Ultomiris",
  "Ultracet",
  "Ultram",
  "Ultram ER",
  "Ultravate",
  "Ultravist",
  "Umeclidinium",
  "Umeclidinium Bromide",
  "Umeclidinium and vilanterol",
  "Unasyn",
  "Undecylenic acid topical",
  "Unisom",
  "Unithroid",
  "Univasc",
  "Uptravi",
  "Ureacin - 20",
  "Urea Cream",
  "Urea topical",
  "Urecholine",
  "Urelle",
  "Urex",
  "Uribel",
  "Urispas",
  "Uristat",
  "Urocit - K",
  "Urogesic - Blue",
  "Urokinase",
  "Uro - MP",
  "Uroxatral",
  "Urso",
  "Ursodiol",
  "Ustekinumab",
  "Utibron Neohaler",
  "Valacyclovir",
  "Valium",
  "Valproic acid",
  "Valsartan",
  "Valtrex",
  "Vancomycin",
  "Varenicline",
  "Vascepa",
  "Vasotec",
  "Veltassa",
  "Venlafaxine",
  "Ventolin",
  "Ventolin HFA",
  "Verapamil",
  "Versed",
  "VESIcare",
  "Viagra",
  "Viberzi",
  "Vibramycin",
  "Vicodin",
  "Victoza",
  "Viibryd",
  "Vimovo",
  "Vimpat",
  "Vistaril",
  "Vitamin B 12",
  "Vitamin C",
  "Vitamin D",
  "Vitamin D2",
  "Vitamin D3",
  "Vitamin E",
  "Vivitrol",
  "Voltaren",
  "Voltaren Gel",
  "Voriconazole",
  "Vortioxetine",
  "Vraylar",
  "Vytorin",
  "Vyvanse",
  "Vyzulta",
  "Wal - finate",
  "Wal - itin",
  "Wal - Zyr D",
  "Warfarin",
  "Warfarin Sodium",
  "Wart Remover",
  "Water for Injection",
  "Welchol",
  "Wellbutrin",
  "Wellbutrin SR",
  "Wellbutrin XL",
  "Westcort",
  "Westhroid",
  "Wild yam",
  "Willow Bark",
  "WinRho",
  "Witch Hazel",
  "Witch hazel topical",
  "Wixela Inhub",
  "Wormwood",
  "Wycillin",
  "Xadago",
  "Xalatan",
  "Xalkori",
  "Xanax",
  "Xanax XR",
  "Xarelto",
  "Xeljanz",
  "Xeljanz XR",
  "Xeloda",
  "Xelpros",
  "Xenazine",
  "Xenical",
  "Xeomin",
  "Xerava",
  "Xgeva",
  "Xhance",
  "Xiaflex",
  "Xifaxan",
  "Xigduo XR",
  "Xiidra",
  "Xofigo",
  "Xofluza",
  "Xolair",
  "Xolegel",
  "Xopenex",
  "Xopenex HFA",
  "Xospata",
  "Xtampza ER",
  "Xtandi",
  "Xulane",
  "Xultophy",
  "XyliMelts",
  "Xylocaine",
  "Xylocaine Jelly",
  "Xylometazoline",
  "Xylometazoline nasal",
  "Xyntha",
  "Xyosted",
  "Xyrem",
  "Xyzal",
  "Y - 90 Zevalin",
  "Yasmin",
  "Yaz",
  "Yellow fever vaccine",
  "Yellow Root",
  "Yervoy",
  "Yescarta",
  "Yohimbe",
  "Yohimbine",
  "Yondelis",
  "Yonsa",
  "Yupelri",
  "Yutiq",
  "Yuvafem",
  "Zaditor",
  "Zaleplon",
  "Zanaflex",
  "Zantac",
  "Zaroxolyn",
  "Zarxio",
  "Zebeta",
  "Zegerid",
  "Zenpep",
  "Zestoretic",
  "Zestril",
  "Zetia",
  "Ziac",
  "Zinc",
  "Ziprasidone",
  "Zithromax",
  "Zocor",
  "Zofran",
  "Zofran ODT",
  "Zoladex",
  "Zoledronic acid",
  "Zolmitriptan",
  "Zoloft",
  "Zolpidem",
  "Zolpidem Tartrate",
  "Zometa",
  "Zomig",
  "Zonegran",
  "Zonisamide",
  "Zostavax",
  "Zosyn",
  "Zovirax",
  "Zubsolv",
  "Zyban",
  "Zyloprim",
  "Zyprexa",
  "Zyrtec",
  "Zyrtec-D",
  "Zytiga",
  "Zyvox",
];
export const deficiencySuggestions = [
  "Xerophthalmia",
  "Rickets",
  "Beriberi",
  "Pellagra",
  "Scurvy",
  "Iron-deficiency anemia",
  "Iodine deficiency",
  "Vitamin D deficiency",
  "Vitamin B12 deficiency",
  "Calcium deficiency",
  "Vitamin A deficiency",
  "Magnesium deficiency",
  "Goitre",
];
export const mentalHealthSuggestions = [
  "Autism",
  "Intellectual development disorder",
  "Global development delay",
  "Communication disorder",
  "Bipolar disorder",
  "Generalized anxiety disorder",
  "Agoraphobia",
  "Social anxiety disorder",
  "Panic disorder",
  "Separation anxiety disorder",
  "Acute stress disorder",
  "Post-traumatic stress",
  "Reactive attachment",
  "Dissociative amnesia",
  "Somatic symptom disorder",
];
